[project]
name = "llm-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "langchain-openai>=1.1.7",
    "langgraph>=1.0.6",
    "langsmith>=0.6.2",
    "python-dotenv>=1.2.1",
]
